token:
  expiration-time : 36000000
  secrit-key: 7e85t6M60:70
za19z5:
 eureka:
  user-name: za1975
  password: '{cipher}AQBhswqjEiNSNwYf0TYSHf6I8tRa4YuWClUwbUlLKzP91VIGr8Tbn8zBuSffzJnr5Yhk6PT02Gt2h8fQ5Go5xWI0sXV2oxYS44+Pdl9jXqfy5+BNKPhCepHJKJd9wS1n1CxsFDVfALqvr8TR5VGo1woHY75gW3yJE1x+IRgwhu4zORSbBag9q6rGJ9N0uD4TWMTCOq9ZrxPBKsJxXURYVD3M8Eq83IPZkQqcgF0DutZp7FKYmiS0udz/2vIZ+DMku/t1o8sift79XD0MpxBi5aebhZiPxGzH8TKOyXSR6ke+buiCYOU3vwmFu3ju5B1vl2Fud3djt3MLq4aElO3JBPDKPKuWp/dRadGdNBOVdioWNLzK9GjkfVc8euaMJC0cJKY='
eureka:
  client:
   eureka-server-d-n-s-name: DESKTOP-Q50BHSL
   service-url:
      defaultZone: http://${za1975.eureka.user-name}:${za1975.eureka.password}@localhost:8761/eureka